image:
  repository: wbuchwalter/kubernetes-webhook-autoscaler
  tag: latest
  pullPolicy: IfNotPresent
options:
  scaleoutwebhook: 
  scaleinwebhook: 
  poolnameregex: 
  drain: false
  ## Optional parameter for sleep time between scaling loops (default: 60)
  sleeptime: 10
  ## Optional parameter for pools to ignore scaling on
  #ignorepools:
  ## Optional parameter denominating number of nodes to spare in a pool after scaling
  #spareagents:
  ## Optional parameter denomi nating the maximum duration (in seconds) an agent can stay idle before being deleted
  #idlethreshold:
  ## Optional parameter denominating the number of extra agents to create when scaling out
  #overprovision:
